pull_request_rules:
  - name: Automatic merge when PR is approved
    conditions:
      - status-success=security/snyk (Distribute Aid)
      -  #approved-reviews-by>=1
    actions:
      merge:
        method: rebase
        rebase_fallback: squash
        bot_account: distributeaid-ci
      label:
        add:
          - mergify
      rebase:
        bot_account: distributeaid-ci
