[build]
    publish = "dist"
    command = '''
    echo $HEAD > .version;
    npm ci --no-audit;
    npx tsc;
    npm run build;
    cp -v web/* dist;
    node scripts/fetchShipments.js > dist/shipments.json;
    node scripts/renderIndex.js > dist/index.html;
    '''