[build]
    publish = "dist"
    command = '''
    echo $HEAD > .version;
    ./node_modules/.bin/tsc;
    npm run build;
    cp -v web/* dist;
    node scripts/fetchShipments.js > dist/shipments.json;
    node scripts/renderIndex.js > dist/index.html;
    '''
[build.environment]
  NODE_VERSION = 12